[package]
name = "placeholder-query-tokio-postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
fortuples.workspace = true
futures-util.workspace = true
lru.workspace = true
parking_lot.workspace = true
placeholder-query-postgres-fetch.workspace = true
placeholder-query-postgres.workspace = true
placeholder-query-runtime.workspace = true
tokio-postgres.workspace = true
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
placeholder-query-core.workspace = true
placeholder-query-macro.workspace = true
